# Generated by Django 4.2.6 on 2023-10-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('votes', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
        migrations.DeleteModel(
            name='URLScrappyModels',
        ),
    ]
