# Generated by Django 4.2.6 on 2023-10-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_moviesmodels_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviesmodels',
            old_name='image_url',
            new_name='img_html',
        ),
    ]
